variable "name" {}
variable "resource_group_name" {}
variable "location" {}
variable "size" {}
variable "admin_username" {}
variable "admin_password" {}
variable "network_interface_ids" {}
variable "os_disk_caching" {}
variable "os_disk_storage_account_type" {}
variable "source_image_reference_publisher" {}
variable "source_image_reference_offer" {}
variable "source_image_reference_sku" {}
variable "source_image_reference_version" {}